# Generated by Django 4.2 on 2023-08-12 14:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cords', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('rate', models.FloatField()),
                ('text', models.CharField(default=False, max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequsetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('tg_id', models.CharField(max_length=255)),
                ('raiting', models.IntegerField(default=3)),
                ('eco_scores', models.IntegerField(default=0)),
                ('jwt_token', models.CharField(max_length=255)),
                ('permition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.permition')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.region')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.complaint')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.requsetstatus')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.complaintcategory'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
    ]
