# Generated by Django 4.2 on 2023-08-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_request_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
