# Generated by Django 4.2 on 2023-08-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_remove_complaint_category_id_complaint_air_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_token',
        ),
    ]
