# Generated by Django 4.2 on 2023-08-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_remove_user_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='air',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='clear',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='environment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='final_eval',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='plants',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='water_obj',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
